// Code generated by goctl. DO NOT EDIT!
// Source: mixin_user.proto

package mixinuser

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MixinUser interface {
		//  创建 MixinUser
		CreateMixinUser(ctx context.Context, in *CreateMixinUserRequest, opts ...grpc.CallOption) (*CreateMixinUserResponse, error)
	}

	defaultMixinUser struct {
		cli zrpc.Client
	}
)

func NewMixinUser(cli zrpc.Client) MixinUser {
	return &defaultMixinUser{
		cli: cli,
	}
}

//  创建 MixinUser
func (m *defaultMixinUser) CreateMixinUser(ctx context.Context, in *CreateMixinUserRequest, opts ...grpc.CallOption) (*CreateMixinUserResponse, error) {
	client := NewMixinUserClient(m.cli.Conn())
	return client.CreateMixinUser(ctx, in, opts...)
}
