// Code generated by goctl. DO NOT EDIT!
// Source: mixin_user.proto

package server

import (
	"context"

	"github.com/leaper-one/power-exchange/rpc/mixinuser-rpc/internal/logic"
	"github.com/leaper-one/power-exchange/rpc/mixinuser-rpc/internal/svc"
	"github.com/leaper-one/power-exchange/rpc/mixinuser-rpc/mixinuser"
)

type MixinUserServer struct {
	svcCtx *svc.ServiceContext
	mixinuser.UnimplementedMixinUserServer
}

func NewMixinUserServer(svcCtx *svc.ServiceContext) *MixinUserServer {
	return &MixinUserServer{
		svcCtx: svcCtx,
	}
}

//  创建 MixinUser
func (s *MixinUserServer) CreateMixinUser(ctx context.Context, in *mixinuser.CreateMixinUserRequest) (*mixinuser.CreateMixinUserResponse, error) {
	l := logic.NewCreateMixinUserLogic(ctx, s.svcCtx)
	return l.CreateMixinUser(in)
}
